### ISSUE TITLE
[TYPO] Typo in button label 

### ISSUE THREAD

**Issue by Jeugeo** [ConnorMolz/todo_app#11]
**Describe the bug**
The cancel button in "Create New Todo" is misspelled

**To Reproduce**
1. Go to 'Create New Todo'
2. The cancel button is misspelled

**Expected behavior**
The Cancel button saying Cancel and not Cancle :)

**Screenshots**
![Screenshot_20240823_192525_todo_app](https://github.com/user-attachments/assets/c6622831-706f-49eb-a427-104bc6d10c27)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22 Ultra
 - OS: Android: One UI

**Additional context**
           -NONE-

**Comment by ConnorMolz** [comment]
I am on it

**Comment by ConnorMolz** [comment]
Change is merged into dev, is coming with version 0.4.0
